### ISSUE TITLE
Missing "libgflags"?

### ISSUE THREAD

**Issue by tham4** [bigbiff/android_device_google_raviole#1]
`FAILED: //system/core/fs_mgr/libsnapshot:snapuserd strip snapuserd
Outputs: out/soong/.intermediates/system/core/fs_mgr/libsnapshot/snapuserd/android_recovery_arm64_armv8-2a_cortex-a55/snapuserd
Error: exited with code: 1
Command: echo "module snapuserd missing dependencies: libgflags" && false
Output:
module snapuserd missing dependencies: libgflags

FAILED: //system/core/fs_mgr/libsnapshot:snapuserd link snapuserd
Outputs: out/soong/.intermediates/system/core/fs_mgr/libsnapshot/snapuserd/android_recovery_arm64_armv8-2a_cortex-a55/unstripped/snapuserd
Error: exited with code: 1
Command: echo "module snapuserd missing dependencies: libgflags" && false
Output:
module snapuserd missing dependencies: libgflags

FAILED: //system/core/fs_mgr/libsnapshot:snapuserd strip snapuserd
Outputs: out/soong/.intermediates/system/core/fs_mgr/libsnapshot/snapuserd/android_vendor_ramdisk_arm64_armv8-2a_cortex-a55/snapuserd
Error: exited with code: 1
Command: echo "module snapuserd missing dependencies: libgflags" && false
Output:
module snapuserd missing dependencies: libgflags

FAILED: //system/core/fs_mgr/libsnapshot:snapuserd link snapuserd
Outputs: out/soong/.intermediates/system/core/fs_mgr/libsnapshot/snapuserd/android_vendor_ramdisk_arm64_armv8-2a_cortex-a55/unstripped/snapuserd
Error: exited with code: 1
Command: echo "module snapuserd missing dependencies: libgflags" && false
Output:
module snapuserd missing dependencies: libgflags
`
Each time I build for oriole, it keeps throwing this error which I don't know what it refers to, I've used all the necessary device-specific files.

**Comment by bigbiff** [comment]
Please make sure you are following https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp

**Comment by tham4** [comment]
I am, I'm going to try build again but without the repository removals that the minimal manifest does

**Comment by tham4** [comment]
I've built it successfully, but whenever I flash the vendor_boot, it goes into a ramdump. I can't seem to figure out if I'm flashing recovery properly

**Comment by bigbiff** [comment]
vendor_boot isn't working at this time. I have been working on it with redfin, but can't figure out the ramdisk issues I am having.

**Comment by tham4** [comment]
Ah okay, thanks for letting me know, I was just questioning if I even had done it correctly
